// Main.createOutputFile() - returns a path for a timestamped log/report file.
//Main.createReportHeader() -  produces the header text used at the top of reports.

import org.junit.jupiter.api.Test;

import java.lang.reflect.Method;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

class CreateFileAndHeaderTest {

    @Test
    void creates_path_and_header_text() throws Exception {
        Method cf = Main.class.getDeclaredMethod("createOutputFile");
        cf.setAccessible(true);
        Path p = (Path) cf.invoke(null);
        assertNotNull(p, "createOutputFile should return a Path");

        Method ch = Main.class.getDeclaredMethod("createReportHeader");
        ch.setAccessible(true);
        StringBuilder sb = (StringBuilder) ch.invoke(null);
        assertTrue(sb.toString().contains("Java Convenience Wrapper Generated by Azure OpenAI"));
    }
}
